#include <stdio.h>
#include <string.h>
#include <libxml/parser.h>
#include <libxml/xmlwriter.h>
#include <libxml/tree.h>


int main(int argc, char **argv)
{
    xmlDocPtr doc = NULL;       /* document pointer */
    xmlNodePtr root_node = NULL, node = NULL, node1 = NULL, pi=NULL;/* node pointers */
    xmlDtdPtr dtd = NULL;       /* DTD pointer */
    xmlAttr *attribute = NULL;
    xmlAttrPtr attr = NULL;
    xmlNs *namespace_decl = NULL;
    xmlTextWriterPtr writer;
    xmlChar *attr_name;
    xmlChar * attr_value;
    char buff[256];
    int i, j, res;

    LIBXML_TEST_VERSION;

	doc = xmlNewDoc(BAD_CAST "1.0");
    root_node = xmlNewNode(NULL, BAD_CAST "Product_Observational");    
    xmlDocSetRootElement(doc, root_node);
    attribute = root_node->properties;
    	 // Create the xml-model processing instruction
    pi = xmlNewPI(BAD_CAST "xml-model", 
    BAD_CAST "href = \"https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1K00.sch\" \
schematypens=\"http://purl.oclc.org/dsdl/schematron\"");
    
    // Add it before the root element
    xmlAddPrevSibling(root_node, pi);

    /* attribute = attribute->next;
    attrVal = xmlTextReaderConstValue(xmlTextReaderPtr reader);*/
    xmlNewChild(root_node, NULL, BAD_CAST "Identification_Area", BAD_CAST NULL);
    xmlNodePtr p1=root_node->children;
    xmlNewChild(p1, NULL, BAD_CAST "logical_identifier", BAD_CAST "urn:nasa:pds:data:mess-h-mdis-5-dem-elevation-v1.0:msgr_dem_usg_sc_j_v02");
    xmlNewChild(p1, NULL, BAD_CAST "version_id", BAD_CAST "1.0");
    xmlNewChild(p1, NULL, BAD_CAST "title", BAD_CAST "mess-h-mdis-5-dem-elevation-v1.0 msgr_dem_usg_sc_j_v02");
    xmlNewChild(p1, NULL, BAD_CAST "information_model_version", BAD_CAST "1.20.0.0");
    xmlNewChild(p1, NULL, BAD_CAST "product_class", BAD_CAST "Product_Observational");
    p1=xmlNewChild(p1, NULL, BAD_CAST "Modification_History", BAD_CAST NULL);
    p1=xmlNewChild(p1, NULL, BAD_CAST "Modification_Detail", BAD_CAST NULL);
    xmlNewChild(p1, NULL, BAD_CAST "Modification_Date", BAD_CAST "2025-10-24");
    xmlNewChild(p1, NULL, BAD_CAST "version_id", BAD_CAST "1.0");
    xmlNewChild(p1, NULL, BAD_CAST "description", BAD_CAST "PDS4 product label generated by SETM libraries");
    p1=p1->parent;p1=p1->parent;p1=p1->parent;
    p1 = xmlNewChild(p1, NULL, BAD_CAST "Observation_Area", BAD_CAST NULL);
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Time_Coordinates", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "start_date_time", BAD_CAST "2025-10-24T09:00:00Z");
	xmlNewChild(p1, NULL, BAD_CAST "stop_date_time", BAD_CAST "2025-10-24T12:00:00Z");
	p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Investigation_Area", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "name", BAD_CAST "messenger");
	xmlNewChild(p1, NULL, BAD_CAST "type", BAD_CAST "Mission");
	p1=xmlNewChild(p1, NULL, BAD_CAST "Internal_Reference", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "lid_reference", BAD_CAST "urn:nasa:pds:investigation.messenger");
	xmlNewChild(p1, NULL, BAD_CAST "reference_type", BAD_CAST "data_to_investigation");
	p1=p1->parent;p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Observing_System", BAD_CAST NULL);
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Observing_System_Component", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "name", BAD_CAST "mercury dual imaging system narrow angle camera");
	xmlNewChild(p1, NULL, BAD_CAST "type", BAD_CAST "Instrument");
	p1=p1->parent;p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Target_Identification", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "name", BAD_CAST "mercury");
	xmlNewChild(p1, NULL, BAD_CAST "planet", BAD_CAST "Planet");
	p1=p1->parent;p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "File_Area_Observational", BAD_CAST NULL);
	p1 = xmlNewChild(p1, NULL, BAD_CAST "File", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "file_name", BAD_CAST "MSGR_DEM_USG_SC_J_V02.IMG");
	p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Array_2D_Image", BAD_CAST NULL);
	p1 = xmlNewChild(p1, NULL, BAD_CAST "offset", BAD_CAST "0");
	attr = xmlSetProp(p1, "unit","byte");
	p1=p1->parent;
	xmlNewChild(p1, NULL, BAD_CAST "axes", BAD_CAST "2");
	xmlNewChild(p1, NULL, BAD_CAST "axis_indes_order", BAD_CAST "Last Index Fastest");
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Element_Array", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "data_type", BAD_CAST "SignedLSB2");
	p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Axis_Array", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "axis_name", BAD_CAST "Line");
	xmlNewChild(p1, NULL, BAD_CAST "elements", BAD_CAST "11520");
	xmlNewChild(p1, NULL, BAD_CAST "sequence_number", BAD_CAST "1");
	p1=p1->parent;
	p1 = xmlNewChild(p1, NULL, BAD_CAST "Axis_Array", BAD_CAST NULL);
	xmlNewChild(p1, NULL, BAD_CAST "axis_name", BAD_CAST "Sample");
	xmlNewChild(p1, NULL, BAD_CAST "elements", BAD_CAST "23040");
	xmlNewChild(p1, NULL, BAD_CAST "sequence_number", BAD_CAST "2");
	p1=p1->parent;p1=p1->parent;p1=p1->parent;p1=p1->parent;

    /*
 *      * Dumping document to stdio or file
 *           */
    xmlSaveFormatFileEnc(argc > 1 ? argv[1] : "-", doc, "UTF-8", 1);

    xmlFreeDoc(doc);

    xmlCleanupParser();

  return 0;
}
